### ISSUE TITLE
Add support for Web Stories plugin

### ISSUE THREAD

**Issue by felixarntz** [felixarntz/wp-gdpr-cookie-notice#11]
`amp-consent` is supported in AMP Stories via a `amp-story-consent` UI component: https://amp.dev/documentation/components/amp-consent/#prompt-ui-for-stories

Support for that should be added based on the Web Stories plugin.

**Comment by swissspidy** [comment]
`web_stories_print_analytics` is the right hook to use in the plugin.

Any chance for adding this anytime soon? :-)
